/****************************************************************************
** Generated by HaiQ
**
** Project name:  viewmda
** Project date:  Mon Dec 6 2010
** Author: 
****************************************************************************/
#include <QApplication>
#include <QWidget>
#include "viewmdawidget.h"
#include "jniftiimage2.h"
#include <QFileInfo>
#include <QDebug>
#include "array3d.h"

///////////////////////////////// ** ////////////////////////////////////
int main(int argc, char *argv[])
{
	QApplication app(argc, argv);

	ViewmdaWidget W;
	W.showNormal();
	if (argc>=2) {
		Mda X;
		if ((QFileInfo(argv[1]).suffix()=="nii")||(QFileInfo(argv[1]).suffix()=="hdr")||(QFileInfo(argv[1]).suffix()=="img")) {
			JNiftiImage2 NI;
			NI.read(argv[1]);
			/*qDebug()  << "# Dimensions:" << NI.dimCount();
			qDebug()  << "Dimensions:" << NI.size(0) << NI.size(1) << NI.size(2) << NI.size(3) << NI.size(4) << NI.size(5);
			qDebug()  << "Resolution:" << NI.resolution(); 
			qDebug()  << "Datatype:" << NI.datatype();*/
			/*{
				Pt3f pt0=NI.xyzPosition(0,0,0); qDebug()  << "Position at (0,0,0):" << QString("%1,%2,%3").arg(pt0.x).arg(pt0.y).arg(pt0.z);
				Pt3f pt1=NI.xyzPosition(1,0,0)-pt0; qDebug()  << "d/di:" << QString("%1,%2,%3").arg(pt1.x).arg(pt1.y).arg(pt1.z);
				Pt3f pt2=NI.xyzPosition(0,1,0)-pt0; qDebug()  << "d/dj:" << QString("%1,%2,%3").arg(pt2.x).arg(pt2.y).arg(pt2.z);
				Pt3f pt3=NI.xyzPosition(0,0,1)-pt0; qDebug()  << "d/dk:" << QString("%1,%2,%3").arg(pt3.x).arg(pt3.y).arg(pt3.z);
			}
			{
				Pt3f pt0=NI.ijkPosition(0,0,0); qDebug()  << "Index of origin:" << QString("%1,%2,%3").arg(pt0.x).arg(pt0.y).arg(pt0.z);
			}*/
			qDebug()  << "HEADER PARAMETERS:" << NI.headerParameters();
			qDebug()  << "TRANSFORMATION" << NI.worldTransformation().toStringList();
			//X=NI.toMda();
			X.allocate(MDA_TYPE_REAL,NI.N1(),NI.N2(),NI.N3(),NI.N4());
			for (int tt=0; tt<NI.N4(); tt++) {
				Array3D tmp0=NI.dataXYZ(tt);
				for (int zz=0; zz<NI.N3(); zz++)
				for (int yy=0; yy<NI.N2(); yy++)
				for (int xx=0; xx<NI.N1(); xx++) {
					X(xx,yy,zz,tt)=tmp0.value(xx,yy,zz);
				}
			}
			//X=NI.dataXYZ(0);
		}
		else {
			X.read(argv[1]);
		}
		W.setArray(X);
	}

	return app.exec();
}

