#############################################################################
# Makefile for building: viewmda
# Generated by qmake (2.01a) (Qt 4.8.4) on: Wed Nov 5 11:58:27 2014
# Project:  viewmda.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile viewmda.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DVIEWMDA -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtTest -I../common/mda -I../common/utils -Ibuild -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L. -lfftw3 -lQtTest -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = main.cpp \
		../common/mda/mda.cpp \
		../common/mda/array2d.cpp \
		../common/mda/array3d.cpp \
		../common/mda/array4d.cpp \
		../common/mda/jniftiimage2.cpp \
		../common/mda/jniftiimage.cpp \
		../common/mda/niftilib/nifti1_io.c \
		../common/mda/niftilib/znzlib.c \
		../common/utils/affinetransformation.cpp \
		../common/utils/jmatrix.cpp \
		../common/utils/textfile.cpp \
		../common/utils/qwait.cpp \
		viewmdamodel.cpp \
		viewmdawidget2d.cpp \
		viewmdawidget1d.cpp \
		viewmdawidget.cpp \
		apply_fft.cpp \
		brightnesstool.cpp \
		export_to_imagej.cpp \
		polygonslices.cpp \
		fftw_library.cpp build/moc_viewmdamodel.cpp \
		build/moc_viewmdawidget2d.cpp \
		build/moc_viewmdawidget1d.cpp \
		build/moc_viewmdawidget.cpp \
		build/moc_brightnesstool.cpp
OBJECTS       = build/main.o \
		build/mda.o \
		build/array2d.o \
		build/array3d.o \
		build/array4d.o \
		build/jniftiimage2.o \
		build/jniftiimage.o \
		build/nifti1_io.o \
		build/znzlib.o \
		build/affinetransformation.o \
		build/jmatrix.o \
		build/textfile.o \
		build/qwait.o \
		build/viewmdamodel.o \
		build/viewmdawidget2d.o \
		build/viewmdawidget1d.o \
		build/viewmdawidget.o \
		build/apply_fft.o \
		build/brightnesstool.o \
		build/export_to_imagej.o \
		build/polygonslices.o \
		build/fftw_library.o \
		build/moc_viewmdamodel.o \
		build/moc_viewmdawidget2d.o \
		build/moc_viewmdawidget1d.o \
		build/moc_viewmdawidget.o \
		build/moc_brightnesstool.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		../common/devcommon.pri \
		../common/mda/jniftiimage.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qtestlib.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		viewmda.pro
QMAKE_TARGET  = viewmda
DESTDIR       = 
TARGET        = viewmda

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_viewmdawidget.h ui_brightnesstool.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: viewmda.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		../common/devcommon.pri \
		../common/mda/jniftiimage.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qtestlib.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtTest.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile viewmda.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
../common/devcommon.pri:
../common/mda/jniftiimage.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qtestlib.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtTest.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile viewmda.pro

dist: 
	@$(CHK_DIR_EXISTS) build/viewmda1.0.0 || $(MKDIR) build/viewmda1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/viewmda1.0.0/ && $(COPY_FILE) --parents ../common/mda/mda.h ../common/mda/array2d.h ../common/mda/array3d.h ../common/mda/array4d.h ../common/mda/jniftiimage2.h ../common/mda/jniftiimage.h ../common/mda/niftilib/nifti1_io.h ../common/mda/niftilib/nifti1.h ../common/mda/niftilib/znzlib.h ../common/utils/affinetransformation.h ../common/utils/jmatrix.h ../common/utils/textfile.h ../common/utils/qwait.h viewmdamodel.h viewmdawidget2d.h viewmdawidget1d.h viewmdawidget.h viewmda_global.h apply_fft.h brightnesstool.h export_to_imagej.h polygonslices.h fftw_library.h fftw3.h build/viewmda1.0.0/ && $(COPY_FILE) --parents main.cpp ../common/mda/mda.cpp ../common/mda/array2d.cpp ../common/mda/array3d.cpp ../common/mda/array4d.cpp ../common/mda/jniftiimage2.cpp ../common/mda/jniftiimage.cpp ../common/mda/niftilib/nifti1_io.c ../common/mda/niftilib/znzlib.c ../common/utils/affinetransformation.cpp ../common/utils/jmatrix.cpp ../common/utils/textfile.cpp ../common/utils/qwait.cpp viewmdamodel.cpp viewmdawidget2d.cpp viewmdawidget1d.cpp viewmdawidget.cpp apply_fft.cpp brightnesstool.cpp export_to_imagej.cpp polygonslices.cpp fftw_library.cpp build/viewmda1.0.0/ && $(COPY_FILE) --parents viewmdawidget.ui brightnesstool.ui build/viewmda1.0.0/ && (cd `dirname build/viewmda1.0.0` && $(TAR) viewmda1.0.0.tar viewmda1.0.0 && $(COMPRESS) viewmda1.0.0.tar) && $(MOVE) `dirname build/viewmda1.0.0`/viewmda1.0.0.tar.gz . && $(DEL_FILE) -r build/viewmda1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_viewmdamodel.cpp build/moc_viewmdawidget2d.cpp build/moc_viewmdawidget1d.cpp build/moc_viewmdawidget.cpp build/moc_brightnesstool.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_viewmdamodel.cpp build/moc_viewmdawidget2d.cpp build/moc_viewmdawidget1d.cpp build/moc_viewmdawidget.cpp build/moc_brightnesstool.cpp
build/moc_viewmdamodel.cpp: ../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h \
		viewmdamodel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) viewmdamodel.h -o build/moc_viewmdamodel.cpp

build/moc_viewmdawidget2d.cpp: viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h \
		viewmdawidget2d.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) viewmdawidget2d.h -o build/moc_viewmdawidget2d.cpp

build/moc_viewmdawidget1d.cpp: viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h \
		viewmdawidget1d.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) viewmdawidget1d.h -o build/moc_viewmdawidget1d.cpp

build/moc_viewmdawidget.cpp: ui_viewmdawidget.h \
		viewmdawidget1d.h \
		viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h \
		viewmdawidget2d.h \
		brightnesstool.h \
		ui_brightnesstool.h \
		viewmdawidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) viewmdawidget.h -o build/moc_viewmdawidget.cpp

build/moc_brightnesstool.cpp: ui_brightnesstool.h \
		brightnesstool.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) brightnesstool.h -o build/moc_brightnesstool.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_viewmdawidget.h ui_brightnesstool.h
compiler_uic_clean:
	-$(DEL_FILE) ui_viewmdawidget.h ui_brightnesstool.h
ui_viewmdawidget.h: viewmdawidget.ui \
		viewmdawidget2d.h \
		viewmdawidget1d.h \
		viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h \
		viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic viewmdawidget.ui -o ui_viewmdawidget.h

ui_brightnesstool.h: brightnesstool.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic brightnesstool.ui -o ui_brightnesstool.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/main.o: main.cpp viewmdawidget.h \
		ui_viewmdawidget.h \
		viewmdawidget1d.h \
		viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h \
		viewmdawidget2d.h \
		brightnesstool.h \
		ui_brightnesstool.h \
		../common/mda/jniftiimage2.h \
		../common/utils/affinetransformation.h \
		../common/utils/jmatrix.h \
		../common/mda/array3d.h \
		../common/mda/array2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

build/mda.o: ../common/mda/mda.cpp ../common/mda/mda.h \
		../common/mda/jniftiimage2.h \
		../common/utils/affinetransformation.h \
		../common/utils/jmatrix.h \
		../common/mda/array3d.h \
		../common/mda/array2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mda.o ../common/mda/mda.cpp

build/array2d.o: ../common/mda/array2d.cpp ../common/mda/array2d.h \
		../common/mda/mda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/array2d.o ../common/mda/array2d.cpp

build/array3d.o: ../common/mda/array3d.cpp ../common/mda/array3d.h \
		../common/mda/array2d.h \
		../common/mda/mda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/array3d.o ../common/mda/array3d.cpp

build/array4d.o: ../common/mda/array4d.cpp ../common/mda/array4d.h \
		../common/mda/array3d.h \
		../common/mda/array2d.h \
		../common/mda/mda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/array4d.o ../common/mda/array4d.cpp

build/jniftiimage2.o: ../common/mda/jniftiimage2.cpp ../common/mda/jniftiimage2.h \
		../common/utils/affinetransformation.h \
		../common/utils/jmatrix.h \
		../common/mda/array3d.h \
		../common/mda/array2d.h \
		../common/mda/mda.h \
		../common/mda/array4d.h \
		../common/utils/qwait.h \
		../common/mda/niftilib/nifti1_io.h \
		../common/mda/niftilib/nifti1.h \
		../common/mda/niftilib/znzlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/jniftiimage2.o ../common/mda/jniftiimage2.cpp

build/jniftiimage.o: ../common/mda/jniftiimage.cpp ../common/mda/jniftiimage.h \
		../common/mda/array3d.h \
		../common/mda/array2d.h \
		../common/mda/mda.h \
		../common/mda/array4d.h \
		../common/mda/niftilib/nifti1.h \
		../common/mda/niftilib/nifti1_io.h \
		../common/mda/niftilib/znzlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/jniftiimage.o ../common/mda/jniftiimage.cpp

build/nifti1_io.o: ../common/mda/niftilib/nifti1_io.c ../common/mda/niftilib/nifti1_io.h \
		../common/mda/niftilib/nifti1.h \
		../common/mda/niftilib/znzlib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/nifti1_io.o ../common/mda/niftilib/nifti1_io.c

build/znzlib.o: ../common/mda/niftilib/znzlib.c ../common/mda/niftilib/znzlib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build/znzlib.o ../common/mda/niftilib/znzlib.c

build/affinetransformation.o: ../common/utils/affinetransformation.cpp ../common/utils/affinetransformation.h \
		../common/utils/jmatrix.h \
		../common/mda/array3d.h \
		../common/mda/array2d.h \
		../common/mda/mda.h \
		../common/utils/textfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/affinetransformation.o ../common/utils/affinetransformation.cpp

build/jmatrix.o: ../common/utils/jmatrix.cpp ../common/utils/jmatrix.h \
		../common/mda/array3d.h \
		../common/mda/array2d.h \
		../common/mda/mda.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/jmatrix.o ../common/utils/jmatrix.cpp

build/textfile.o: ../common/utils/textfile.cpp ../common/utils/textfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/textfile.o ../common/utils/textfile.cpp

build/qwait.o: ../common/utils/qwait.cpp ../common/utils/qwait.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qwait.o ../common/utils/qwait.cpp

build/viewmdamodel.o: viewmdamodel.cpp viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/viewmdamodel.o viewmdamodel.cpp

build/viewmdawidget2d.o: viewmdawidget2d.cpp viewmdawidget2d.h \
		viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/viewmdawidget2d.o viewmdawidget2d.cpp

build/viewmdawidget1d.o: viewmdawidget1d.cpp viewmdawidget1d.h \
		viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/viewmdawidget1d.o viewmdawidget1d.cpp

build/viewmdawidget.o: viewmdawidget.cpp viewmdawidget.h \
		ui_viewmdawidget.h \
		viewmdawidget1d.h \
		viewmdamodel.h \
		../common/mda/mda.h \
		viewmda_global.h \
		polygonslices.h \
		viewmdawidget2d.h \
		brightnesstool.h \
		ui_brightnesstool.h \
		apply_fft.h \
		export_to_imagej.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/viewmdawidget.o viewmdawidget.cpp

build/apply_fft.o: apply_fft.cpp apply_fft.h \
		../common/mda/mda.h \
		fftw_library.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/apply_fft.o apply_fft.cpp

build/brightnesstool.o: brightnesstool.cpp brightnesstool.h \
		ui_brightnesstool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/brightnesstool.o brightnesstool.cpp

build/export_to_imagej.o: export_to_imagej.cpp export_to_imagej.h \
		../common/mda/mda.h \
		viewmda_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/export_to_imagej.o export_to_imagej.cpp

build/polygonslices.o: polygonslices.cpp polygonslices.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/polygonslices.o polygonslices.cpp

build/fftw_library.o: fftw_library.cpp fftw_library.h \
		../common/mda/mda.h \
		fftw3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/fftw_library.o fftw_library.cpp

build/moc_viewmdamodel.o: build/moc_viewmdamodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_viewmdamodel.o build/moc_viewmdamodel.cpp

build/moc_viewmdawidget2d.o: build/moc_viewmdawidget2d.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_viewmdawidget2d.o build/moc_viewmdawidget2d.cpp

build/moc_viewmdawidget1d.o: build/moc_viewmdawidget1d.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_viewmdawidget1d.o build/moc_viewmdawidget1d.cpp

build/moc_viewmdawidget.o: build/moc_viewmdawidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_viewmdawidget.o build/moc_viewmdawidget.cpp

build/moc_brightnesstool.o: build/moc_brightnesstool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_brightnesstool.o build/moc_brightnesstool.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

